language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging

# Build
  - docker build -t udagram-api-feed ./udagram-api-feed:v6
  - docker build -t udagram-api-user ./udagram-api-user:v6
  - docker build -t udagram-frontend ./udagram-frontend:v6
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy:v6

# Tagging
  - docker tag udagram-api-feed nghiadthp/udagram-api-feed
  - docker tag udagram-api-user nghiadthp/udagram-api-user
  - docker tag udagram-frontend nghiadthp/udagram-frontend
  - docker tag udagram-reverseproxy nghiadthp/udagram-reverseproxy

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push nghiadthp/udagram-api-feed:v6
  - docker push nghiadthp/udagram-api-user:v6
  - docker push nghiadthp/udagram-frontend:v6
  - docker push nghiadthp/udagram-reverseproxy:v6