apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: backend-user
  name: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
      - image: nghiadthp/udagram-api-user:v1
        name: udagram-api-user 
        imagePullPolicy: Always  
        env:
        - name: URL
          value: http://localhost:8080
        - name: JWT_SECRET
          value: hello
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_HOST
          value: database-1.c8l6rpcx6w6p.us-east-1.rds.amazonaws.com
        - name: POSTGRES_PASSWORD
          value: SpringSpring123
        - name: POSTGRES_USERNAME
          value: postgres
        - name: AWS_BUCKET
          value: arn:aws:s3:::udacity-project3-nghiadt
      restartPolicy: Always

